[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.86", default-features = true }
tokio = { version = "1.39.2", features = [
    "io-util",
    "macros",
    "net",
    "rt-multi-thread",
    "sync",
] }

[[bin]]
name = "tcp"
path = "./src/server/tcp.rs"

[[bin]]
name = "udp"
path = "./src/server/udp.rs"
