[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.39.2", features = ["full"] }
anyhow = { version="1.0", default-features = true }

[[bin]]
name = "server"
path = "./src/server/main.rs"
