[package]
name = "srv"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "*", default-features = true }
tokio = { version = "*", features = [
    "io-util",
    "macros",
    "net",
    "rt-multi-thread",
    "sync",
    "time",
] }
zerocopy = { version = "*", features = ["derive"] }

[lib]
name = "srv"
path = "srv/lib.rs"

[[bin]]
name = "tcp"
path = "./srv/tcp.rs"

[[bin]]
name = "udp"
path = "./srv/udp.rs"

[[bin]]
name = "server"
path = "./srv/server.rs"
