[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.86", default-features = true }
bytemuck = { version = "1.16.3", features = ["derive"] }
lazy_static = "1.5.0"
tokio = { version = "1.39.2", features = [
    "io-util",
    "macros",
    "net",
    "rt-multi-thread",
    "sync",
    "time",
] }

[[bin]]
name = "tcp"
path = "./src/server/tcp.rs"

[[bin]]
name = "udp"
path = "./src/server/udp.rs"

[[bin]]
name = "pong"
path = "./src/server/pong.rs"
