[package]
name = "srv"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.86", default-features = true }
lazy_static = "1.5.0"
tokio = { version = "1.39.2", features = [
    "io-util",
    "macros",
    "net",
    "rt-multi-thread",
    "sync",
    "time",
] }

[[bin]]
name = "tcp"
path = "./srv/tcp.rs"

[[bin]]
name = "udp"
path = "./srv/udp.rs"
